name: postman

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      # Set up golang env
      - name: Set up GO 1.14.4
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.4
          id: go
      - name: Checkout the source code
        uses: actions/checkout@v1
      - name: Cache postman Library
        uses: actions/cache@v1
        env:
          cache-name: postman-cache
        with:
          path: $GOPATH/pkg/mod
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./go.lock') }}
      - name: Build
        run: make
